name: CI

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.java'
      - '**.gradle'
      - '**.kts'
      - 'gradle/**'
      - '.github/workflows/**'
      - '!**.md'
      - '!LICENSE'
      - '!.gitignore'
      - '!.gitattributes'
  push:
    branches:
      - main
    paths:
      - '**.java'
      - '**.gradle'
      - '**.kts'
      - 'gradle/**'
      - '.github/workflows/**'
      - '!**.md'
      - '!LICENSE'
      - '!.gitignore'
      - '!.gitattributes'
  workflow_dispatch:

jobs:
  gradlewTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Test with Gradle
        run: ./gradlew test

  gradlewNativeCompile:
    name: Build native image for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: "21"
          distribution: "graalvm-community"
          native-image-musl: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Compile Native Image with GraalVM
        run: ./gradlew nativeCompile

      - name: Run Built Native Image
        run: ./app/build/native/nativeCompile/pkce-code-challenge-generator dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk
